### ISSUE TITLE
Time-stamp error/unable to parse when feeding data into influxDB

### ISSUE THREAD

**Issue by theseal666** [joabakk/signalk-polar#61]
I have constant errors on the data from this plugin when I want to feed them into influx.

"Jun 12 23:18:44 Error: A 400 Bad Request error occurred: {"error":"partial write: unable to parse 'performance.beatAngle,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0.9876577115566776 NaN': bad timestamp\nunable to parse 'performance.beatAngleTargetSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=3.1381119060994607 NaN': bad timestamp\nunable to parse 'performance.beatAngleVelocityMadeGood,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=1.4573499257480211 NaN': bad timestamp\nunable to parse 'performance.targetAngle,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0.9876577115566776 NaN': bad timestamp\nunable to parse 'performance.targetSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=3.1381119060994607 NaN': bad timestamp\nunable to parse 'performance.gybeAngle,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=3.1285888647430173 NaN': bad timestamp\nunable to parse 'performance.gybeAngleTargetSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=13.015447741691206 NaN': bad timestamp\nunable to parse 'performance.gybeAngleVelocityMadeGood,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=-13.014347310694532 NaN': bad timestamp\nunable to parse 'performance.polarSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=5.504556950043316 NaN': bad timestamp\nunable to parse 'performance.polarSpeedRatio,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0 NaN': bad timestamp\nunable to parse 'environment.wind.speedTrue,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=11.27 NaN': bad timestamp\nunable to parse 'environment.wind.angleTrueWater,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=1.4573499257480211 NaN': bad timestamp\nunable to parse 'performance.velocityMadeGood,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0 NaN': bad timestamp\nunable to parse 'performance.beatAngle,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0.6151575271528897 NaN': bad timestamp\nunable to parse 'performance.beatAngleTargetSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=2.8 NaN': bad timestamp\nunable to parse 'performance.beatAngleVelocityMadeGood,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=1.4667 NaN': bad timestamp\nunable to parse 'performance.targetAngle,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0.6151575271528897 NaN': bad timestamp\nunable to parse 'performance.targetSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=2.8 NaN': bad timestamp\nunable to parse 'performance.gybeAngle,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=3.1182664161777955 NaN': bad timestamp\nunable to parse 'performance.gybeAngleTargetSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=13.015447741691206 NaN': bad timestamp\nunable to parse 'performance.gybeAngleVelocityMadeGood,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=-13.01190696279637 NaN': bad timestamp\nunable to parse 'performance.polarSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=2.1606672140356946 NaN': bad timestamp\nunable to parse 'performance.polarSpeedRatio,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0 NaN': bad timestamp\nunable to parse 'environment.wind.speedTrue,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=9.99 NaN': bad timestamp\nunable to parse 'environment.wind.angleTrueWater,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=1.6063 NaN': bad timestamp\nunable to parse 'performance.velocityMadeGood,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0 NaN': bad timestamp\nunable to parse 'performance.beatAngle,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0.6151575271528897 NaN': bad timestamp\nunable to parse 'performance.beatAngleTargetSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=2.8 NaN': bad timestamp\nunable to parse 'performance.beatAngleVelocityMadeGood,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=1.6063 NaN': bad timestamp\nunable to parse 'performance.gybeAngle,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=3.1182664161777955 NaN': bad timestamp\nunable to parse 'performance.gybeAngleTargetSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=13.015447741691206 NaN': bad timestamp\nunable to parse 'performance.gybeAngleVelocityMadeGood,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=-13.01190696279637 NaN': bad timestamp\nunable to parse 'performance.targetAngle,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=3.1182664161777955 NaN': bad timestamp\nunable to parse 'performance.targetSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=13.015447741691206 NaN': bad timestamp\nunable to parse 'performance.polarSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=3.68 NaN': bad timestamp\nunable to parse 'performance.polarSpeedRatio,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0 NaN': bad timestamp\nunable to parse 'environment.wind.speedTrue,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=10.340335952885109 NaN': bad timestamp\nunable to parse 'environment.wind.angleTrueWater,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=1.3619 NaN': bad timestamp\nunable to parse 'performance.velocityMadeGood,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0 NaN': bad timestamp\nunable to parse 'performance.beatAngle,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0.9876577115566776 NaN': bad timestamp\nunable to parse 'performance.beatAngleTargetSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=3.1381119060994607 NaN': bad timestamp\nunable to parse 'performance.beatAngleVelocityMadeGood,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=1.3619 NaN': bad timestamp\nunable to parse 'performance.targetAngle,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0.9876577115566776 NaN': bad timestamp\nunable to parse 'performance.targetSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=3.1381119060994607 NaN': bad timestamp\nunable to parse 'performance.gybeAngle,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=3.1285888647430173 NaN': bad timestamp\nunable to parse 'performance.gybeAngleTargetSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=13.015447741691206 NaN': bad timestamp\nunable to parse 'performance.gybeAngleVelocityMadeGood,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=-13.014347310694532 NaN': bad timestamp\nunable to parse 'performance.polarSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=3.55 NaN': bad timestamp\nunable to parse 'performance.polarSpeedRatio,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0 NaN': bad timestamp\nunable to parse 'environment.wind.speedTrue,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=10.35 NaN': bad timestamp\nunable to parse 'environment.wind.angleTrueWater,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=1.4143 NaN': bad timestamp\nunable to parse 'performance.velocityMadeGood,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0 NaN': bad timestamp\nunable to parse 'performance.beatAngle,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0.9876577115566776 NaN': bad timestamp\nunable to parse 'performance.beatAngleTargetSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=3.1381119060994607 NaN': bad timestamp\nunable to parse 'performance.beatAngleVelocityMadeGood,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=1.2921 NaN': bad timestamp\nunable to parse 'performance.targetAngle,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0.9876577115566776 NaN': bad timestamp\nunable to parse 'performance.targetSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=3.1381119060994607 NaN': bad timestamp\nunable to parse 'performance.gybeAngle,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=3.1285888647430173 NaN': bad timestamp\nunable to parse 'performance.gybeAngleTargetSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=13.015447741691206 NaN': bad timestamp\nunable to parse 'performance.gybeAngleVelocityMadeGood,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=-13.014347310694532 NaN': bad timestamp\nunable to parse 'performance.polarSpeed,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=2.2121116715127345 NaN': bad timestamp\nunable to parse 'performance.polarSpeedRatio,context=vessels.urn:mrn:signalk:uuid:52133a24-d0a3-4239-9d61-b0fd66fc39a2,source=calculated.signalk-polar value=0 NaN': bad timestamp dropped=0"} at IncomingMessage.Create.res.on (/home/pi/.signalk/node_modules/influx/lib/src/pool.js:50:38) at IncomingMessage.emit (events.js:203:15) at endReadableNT (_stream_readable.js:1145:12) at process._tickCallback (internal/process/next_tick.js:63:19) "

**Comment by joabakk** [comment]
the pushDelta function should be replaced with app.handleMessage. This way, the timestamp will be added and this message should disappear.
