### ISSUE TITLE
Unable to show "user input polars"

### ISSUE THREAD

**Issue by theseal666** [joabakk/signalk-polar#62]
I have tried to put in the date from our ORCi-sheet from jester, and from the preloaded polars but the never show up in the webbapp.

What can I look in to?

**Comment by theseal666** [comment]
Pictures from my problems
![Screenshot 2021-06-15 at 11 56 22](https://user-images.githubusercontent.com/25456616/122215228-435f9880-ceab-11eb-99f7-31311f63bdd4.png)
![Screenshot 2021-06-15 at 11 56 31](https://user-images.githubusercontent.com/25456616/122215234-4490c580-ceab-11eb-9d8a-e4b2fd1b94e6.png)
![Screenshot 2021-06-15 at 11 57 06](https://user-images.githubusercontent.com/25456616/122215236-45295c00-ceab-11eb-9c07-96855235f115.png)


Don't mind the bodged data, it is from a faulty sensor/voltage-problems.

**Comment by joabakk** [comment]
I'm tearing my hair out here trying to restore this function. I'm stuck here: https://github.com/joabakk/signalk-polar/blob/master/index.js#L138-L152. The query works in SQLite, but not in the script...

**Comment by joabakk** [comment]
Closing this issue as I have just published a new version. Please feel free to reopen if this is still an issue
