### ISSUE TITLE
Not working right under 9 Kts TWS

### ISSUE THREAD

**Issue by RhumbRunner** [joabakk/signalk-polar#82]
I've been putting the signalk-polar v3.0.0 thru it's paces from home using SKsim to provide precise TWS/TWA data to the plugin. I'm getting the expected data at 6 kts of wind and at 10 kts and above. 8 kts is showing the data from 6 and anything below 6 shows the 6 kts data.  Starting at 9 kts I'm getting interpolated data for 11, 13, 15 and so on that looks right on the money. I'm including my polar file as it is in the /.signalk/plugin-config-data/signalk-polar

[586f602e-df5d-4752-896b-930acfdff01.txt](https://github.com/joabakk/signalk-polar/files/9690960/586f602e-df5d-4752-896b-930acfdff01.txt)

**Comment by RhumbRunner** [comment]
I wish I knew how to post a revision to the codebase.

Ok, dove deeper into the code and the problem. Attached is the revised code. Basically it was not looking at the right tws column it was always looking at the column lower than the current tws. It should have been looking for the higher tws column if you're above the lowest column value or the highest column if you're above it's value. ie 0 to 6 kts should look at the 6 kts column and 6.00001 you should start looking at the 8 kts column and interpolating between the 6 and 8 kt values and so on up to the max at 20 kts and then just use the 20 kts column for tws above that.  The new code also tries to interpolate between 0 and 6 kts but it's probably not the most accurate but I figured it couldn't hurt... 

[main.txt](https://github.com/joabakk/signalk-polar/files/9712370/main.txt)

**Comment by joabakk** [comment]
Implemented the suggestion, closing here
